# Generated by Django 4.0.1 on 2022-01-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsongrec', '0002_music_filesize_video_filesize_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/video'),
        ),
    ]
